name: line_white_signup_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
    color: "#5892F6"
    image: assets/img/logo.png
    android: true
    ios: true
    web: true
    fullscreen: true
